build:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/fpallas/blog:latest .
    - docker push $CI_REGISTRY/fpallas/blog:latest
